FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

# Install basic system dependencies
#RUN apt-get update && apt-get install -y \
#    wget unzip git cmake build-essential libglib2.0-0 libsm6 libxext6 libxrender-dev \
#    python3 python3-pip python3-venv && \
#    rm -rf /var/lib/apt/lists/*
# Install Python 3.10 explicitly
RUN apt-get update && apt-get install -y \
    software-properties-common && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && \
    apt-get install -y python3.10 python3.10-venv python3.10-dev python3.10-distutils && \
    ln -sf /usr/bin/python3.10 /usr/bin/python3 && \
    wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && \
    rm get-pip.py

RUN apt-get update && apt-get install -y python3-pyqt5 pkg-config libhdf5-dev


# Upgrade pip
RUN pip install --upgrade pip

# Install PyTorch and related
#RUN pip install torch==2.1.0+cu118 torchvision==0.16.0+cu118 torchaudio==2.1.0+cu118 --index-url https://download.pytorch.org/whl/cu118
RUN pip install torch==2.1.0+cu118 \
                torchvision==0.16.0+cu118 \
                torchaudio==2.1.0+cu118 \
                --index-url https://download.pytorch.org/whl/cu118

#print a python version currently used

#RUN python3 -c "import torch; print(torch.cuda.is_available())"

# Copy only requirements first
COPY requirements.txt /tmp/requirements.txt

# Install all pip dependencies
RUN pip install -r /tmp/requirements.txt

# Now copy the DEVO code
COPY . /workspace
WORKDIR /workspace

# Install DEVO package
RUN pip install .

# Set bash as default
CMD ["/bin/bash"]
