name: devo
channels:
  - pyg
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - cudatoolkit=11.8  # CUDA 11.8
#  - pytorch=2.1.0  # PyTorch 2.1.0
#  - pytorch-cuda=11.8  # CUDA-enabled PyTorch version
#  - torchvision  # No specific version
#  - torchaudio  # No specific version
  - pip
  - pip:
#      - torch-scatter -f https://data.pyg.org/whl/torch-2.1.0+cu118.html  # Install torch-scatter for PyTorch 2.1.0
      - plyfile
      - argcomplete
      - beautifulsoup4
      - cmake
      - colorama
      - configargparse
      - evo
      - filelock
      - gdown
      - h5py
      - hdf5plugin
      - lz4
      - natsort
      - numba
      - opencv-python
      - pandas
      - pygments
      - pyqt5
      - pytz
      - pyyaml
      - rosbags
      - ruamel-yaml
      - ruamel-yaml-clib
      - seaborn
      - soupsieve
      - tabulate
      - yacs
      - zstandard
